### ISSUE TITLE
Other Non-Steam Games Gone?

### ISSUE THREAD

**Issue by markthewolf90** [BrianLima/UWPHook#38] opened 2019-11-07 19:04 UTC
I couldn't replicate this issue, so it was likely just some freak occurence, but the first time I ran UWPHook and exported a program, it removed the rest of the non-steam games that were in my library.

**Comment by BrianLima** [comment] 2020-05-02 19:41
The app tries to load your current VRF file, it contains all the non-steam games defined in it, it then creates a new entry and appends it to the file. Maybe somehow it got currupted in the process, ill dig further into it.

**Comment by BrianLima** [comment] 2020-11-08 14:31
Hey, this was actually a problem, caused by one of the dependencies of the project, it got fixed in the previous release 2.6.0 by mr #43 .

**Closed by BrianLima** 2020-11-08 14:31 UTC
